package createroom

import (
	"encoding/json"
	"strings"
	"testing"
	"time"

	"turn-tracker/backend/core"
	"turn-tracker/backend/handlers/joinroom"
	"turn-tracker/backend/handlers/startturn"
	"turn-tracker/backend/handlers/updateprofile"
	"turn-tracker/backend/test_helpers"
	"turn-tracker/backend/types"
)

func setupTestMessageRouter() core.MessageHandler {
	return func(hub *core.Hub, client *core.Client, msg *types.Message) {
		switch msg.Type {
		case "create_room":
			var data CreateRoomData
			json.Unmarshal(msg.Data, &data)
			HandleCreateRoom(hub, client, data.RoomID, data.DisplayName, data.Color)
		case "join_room":
			var data joinroom.JoinRoomData
			if err := json.Unmarshal(msg.Data, &data); err != nil {
				errorMsg, _ := types.NewErrorMessage("Invalid join_room data")
				client.Send <- errorMsg
				return
			}
			roomID := strings.ToUpper(data.RoomID)
			joinroom.HandleJoinRoom(hub, client, roomID, data.DisplayName, data.Color)
		case "update_profile":
			var data updateprofile.UpdateProfileData
			if err := json.Unmarshal(msg.Data, &data); err != nil {
				errorMsg, _ := types.NewErrorMessage("Invalid update_profile data")
				client.Send <- errorMsg
				return
			}
			updateprofile.HandleUpdateProfile(hub, client, data.DisplayName, data.Color)
		case "start_turn":
			var data startturn.StartTurnData
			if err := json.Unmarshal(msg.Data, &data); err != nil {
				errorMsg, _ := types.NewErrorMessage("Invalid start_turn data")
				client.Send <- errorMsg
				return
			}
			startturn.HandleStartTurn(hub, client, data.CurrentTurn, data.NewTurn)
		default:
			errorMsg, _ := types.NewUnknownMessageTypeError(msg.Type)
			client.Send <- errorMsg
		}
	}
}

func TestCreateRoomMessageFormat(t *testing.T) {
	server := test_helpers.SetupTestServer(setupTestMessageRouter())
	defer server.Cleanup()

	client, err := test_helpers.ConnectTestClient(server.Server.URL)
	if err != nil {
		t.Fatalf("Failed to connect: %v", err)
	}
	defer client.Close()

	// Wait a moment for connection to be fully established
	time.Sleep(100 * time.Millisecond)

	// Send create_room message
	createData := map[string]interface{}{
		"display_name": "TestUser",
		"color":        "#FF5733",
	}

	err = client.SendMessage("create_room", createData)
	if err != nil {
		t.Fatalf("Failed to send message: %v", err)
	}

	// Wait for room_created response
	response, err := client.ReceiveMessage(5 * time.Second)
	if err != nil {
		t.Fatalf("Failed to receive response: %v", err)
	}

	// Validate message type
	if response.Type != "room_created" {
		t.Errorf("Expected message type 'room_created', got '%s'", response.Type)
	}

	// Validate JSON structure
	var data RoomCreatedData
	err = json.Unmarshal(response.Data, &data)
	if err != nil {
		t.Fatalf("Failed to unmarshal response data: %v", err)
	}

	// Validate fields
	if data.RoomID == "" {
		t.Error("RoomID should not be empty")
	}
	if len(data.RoomID) != 6 {
		t.Errorf("RoomID should be 6 characters, got %d", len(data.RoomID))
	}
	if len(data.Peers) != 1 {
		t.Errorf("Expected 1 peer, got %d", len(data.Peers))
	}
	if data.Peers[0].DisplayName != "TestUser" {
		t.Errorf("Expected DisplayName 'TestUser', got '%s'", data.Peers[0].DisplayName)
	}
	if data.Peers[0].Color != "#FF5733" {
		t.Errorf("Expected Color '#FF5733', got '%s'", data.Peers[0].Color)
	}
	if data.CurrentTurn != nil {
		t.Error("CurrentTurn should be nil for new room")
	}
}

func TestCreateRoomWithoutProfile(t *testing.T) {
	server := test_helpers.SetupTestServer(setupTestMessageRouter())
	defer server.Cleanup()

	client, err := test_helpers.ConnectTestClient(server.Server.URL)
	if err != nil {
		t.Fatalf("Failed to connect: %v", err)
	}
	defer client.Close()

	time.Sleep(100 * time.Millisecond)

	// Send create_room message without display_name or color
	err = client.SendMessage("create_room", map[string]interface{}{})
	if err != nil {
		t.Fatalf("Failed to send message: %v", err)
	}

	response, err := client.ReceiveMessage(5 * time.Second)
	if err != nil {
		t.Fatalf("Failed to receive response: %v", err)
	}

	if response.Type != "room_created" {
		t.Fatalf("Expected room_created, got %s", response.Type)
	}

	var data RoomCreatedData
	json.Unmarshal(response.Data, &data)

	// Server should generate random display_name and color
	if data.Peers[0].DisplayName == "" {
		t.Error("DisplayName should be generated by server")
	}
	if data.Peers[0].Color == "" {
		t.Error("Color should be generated by server")
	}
}
