// Generated by React Router

import "react-router"

declare module "react-router" {
  interface Register {
    pages: Pages
    routeFiles: RouteFiles
    routeModules: RouteModules
  }
}

type Pages = {
  "/": {
    params: {};
  };
  "/offline": {
    params: {};
  };
  "/game/:gameID?": {
    params: {
      "gameID"?: string;
    };
  };
  "/game/:gameID?/turn/:clientID": {
    params: {
      "gameID"?: string;
      "clientID": string;
    };
  };
  "/options": {
    params: {};
  };
  "/dev/toasts": {
    params: {};
  };
};

type RouteFiles = {
  "root.tsx": {
    id: "root";
    page: "/" | "/offline" | "/game/:gameID?" | "/game/:gameID?/turn/:clientID" | "/options" | "/dev/toasts";
  };
  "components/Home.tsx": {
    id: "components/Home";
    page: "/";
  };
  "components/BackendUnavailable.tsx": {
    id: "components/BackendUnavailable";
    page: "/offline";
  };
  "components/GameContainer.tsx": {
    id: "components/GameContainer";
    page: "/game/:gameID?" | "/game/:gameID?/turn/:clientID";
  };
  "components/GameHome.tsx": {
    id: "components/GameHome";
    page: "/game/:gameID?";
  };
  "components/PlayerTurn.tsx": {
    id: "components/PlayerTurn";
    page: "/game/:gameID?/turn/:clientID";
  };
  "components/OptionsPage.tsx": {
    id: "components/OptionsPage";
    page: "/options";
  };
  "components/ToastExamples.tsx": {
    id: "components/ToastExamples";
    page: "/dev/toasts";
  };
};

type RouteModules = {
  "root": typeof import("./src/root.tsx");
  "components/Home": typeof import("./src/components/Home.tsx");
  "components/BackendUnavailable": typeof import("./src/components/BackendUnavailable.tsx");
  "components/GameContainer": typeof import("./src/components/GameContainer.tsx");
  "components/GameHome": typeof import("./src/components/GameHome.tsx");
  "components/PlayerTurn": typeof import("./src/components/PlayerTurn.tsx");
  "components/OptionsPage": typeof import("./src/components/OptionsPage.tsx");
  "components/ToastExamples": typeof import("./src/components/ToastExamples.tsx");
};